SELECT
    T.CARD_NUMBER
FROM TRANSACTIONS T
         INNER JOIN COMMERCE C ON C.COMMERCE_ID = T.COMMERCE_ID
         LEFT JOIN DBO.TEMPBIN TB ON TB.BIN = LEFT(T.CARD_NUMBER, 6)
WHERE T.TRANSACTION_TYPE IN ('Venta', 'CheckOut', 'Devolución')
  AND T.TRANSACTION_STATUS = 'Aprobada'
  AND T.PROCESSED = 1
  AND TB.TipoProducto IS NULL
